### PR TITLE
Minor edits

### PR DESCRIPTION
**Pull request by lima3w**
Adjusted spelling/spacing for console logs.
Also added output of negative version number, in order to debug the plugin version

### CODE REVIEW

**Comment by N07070** [comment]
They is a quote mismatch in the pull request it seems. You should put all the text in " quotes and the values in ' quotes. 

Could you confirm this and resubmit a pull? 

Thanks! 😉

**Comment by lima3w** [comment]
Is this what you mean?

**Comment by N07070** [comment]
Yes, all seems good to run! Thanks for the pull request, feel free to add plugins too, for anything and everything! 

Have a nice day!

**Comment by lima3w** [comment]
Thanks! I'll see if I can add any decent plugins

**Pull request merged**
